In [1]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
np.add(2,5)

7

In [3]:
np.subtract(4,7) 

-3

In [4]:
np.multiply(4,2)

8

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,2),54)

array([[54, 54],
       [54, 54],
       [54, 54],
       [54, 54]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [10]:
np.random.random((3,6))

array([[0.62299994, 0.75722214, 0.62735532, 0.04823603, 0.71571965,
        0.92777343],
       [0.33862718, 0.30285191, 0.49952986, 0.36494392, 0.82579605,
        0.18462028],
       [0.44040263, 0.73787606, 0.24734791, 0.1832878 , 0.9948938 ,
        0.7499953 ]])

In [11]:
a=np.eye(4)

In [12]:
np.empty(3)

array([0. , 2.5, 5. ])

In [13]:
c=np.random.randint(0,10,(3,3))
c

array([[8, 4, 0],
       [2, 5, 2],
       [9, 6, 8]])

In [14]:
np.shape(a)

(4, 4)

In [15]:
np.size(a)

16

In [16]:
a.dtype

dtype('float64')

In [17]:
a.data

In [18]:
a.itemsize

8

In [19]:
a.ndim

2

In [20]:
b=np.random.default_rng(1)
b

Generator(PCG64) at 0x7F9411C3E048

In [21]:
c=np.random.randint(0,10,(3,3))
c

array([[8, 1, 0],
       [0, 0, 8],
       [8, 5, 0]])

In [22]:
c.min()

0

In [23]:
c.max()

8

In [24]:
c.mean()

3.3333333333333335

In [25]:
c.sum()

30

In [26]:
np.exp(c)

array([[2.98095799e+03, 2.71828183e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 2.98095799e+03],
       [2.98095799e+03, 1.48413159e+02, 1.00000000e+00]])

In [27]:
np.random.seed(0)
np.random.random((3,5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [28]:
c.ravel()

array([8, 1, 0, 0, 0, 8, 8, 5, 0])

In [29]:
np.abs(c)

array([[8, 1, 0],
       [0, 0, 8],
       [8, 5, 0]])

In [30]:
np.pi

3.141592653589793

In [31]:
np.sin(c)

array([[ 0.98935825,  0.84147098,  0.        ],
       [ 0.        ,  0.        ,  0.98935825],
       [ 0.98935825, -0.95892427,  0.        ]])

In [32]:
np.cos(c)

array([[-0.14550003,  0.54030231,  1.        ],
       [ 1.        ,  1.        , -0.14550003],
       [-0.14550003,  0.28366219,  1.        ]])

In [33]:
np.tan(c)

array([[-6.79971146,  1.55740772,  0.        ],
       [ 0.        ,  0.        , -6.79971146],
       [-6.79971146, -3.38051501,  0.        ]])

In [34]:
np.arcsin(0.5)

0.5235987755982989

In [35]:
np.arccos(0.5)

1.0471975511965979

In [36]:
np.arctan(0.5)

0.4636476090008061

In [37]:
np.log(c)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[2.07944154, 0.        ,       -inf],
       [      -inf,       -inf, 2.07944154],
       [2.07944154, 1.60943791,       -inf]])

In [38]:
np.log2(c)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[3.        , 0.        ,       -inf],
       [      -inf,       -inf, 3.        ],
       [3.        , 2.32192809,       -inf]])

In [39]:
np.log10(c)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([[0.90308999, 0.        ,       -inf],
       [      -inf,       -inf, 0.90308999],
       [0.90308999, 0.69897   ,       -inf]])

In [40]:
np.add.reduce(c)

array([16,  6,  8])

In [41]:
np.multiply.reduce(c)

array([0, 0, 0])

In [42]:
np.add.accumulate(c)

array([[ 8,  1,  0],
       [ 8,  1,  8],
       [16,  6,  8]])

In [43]:
np.multiply.accumulate(c)

array([[8, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
np.power(3,5)

243

In [45]:
np.hsplit(c,3)

[array([[8],
        [0],
        [8]]), array([[1],
        [0],
        [5]]), array([[0],
        [8],
        [0]])]

In [46]:
np.vsplit(c,3)

[array([[8, 1, 0]]), array([[0, 0, 8]]), array([[8, 5, 0]])]

In [47]:
np.absolute(c)

array([[8, 1, 0],
       [0, 0, 8],
       [8, 5, 0]])

In [48]:
np.prod(c)

0

In [49]:
np.std(c)

3.6209268304000717

In [50]:
np.var(c)

13.11111111111111